stages:
  - repoTest
  - praktikum1
  - praktikum2
  - praktikum3
  - praktikum4
  - praktikum5
  - praktikum6
  - praktikum7
  - praktikum8
  - praktikum9
  - praktikum10
  - praktikum11

## Templates ##
  
.linux:test: &linux_test_job
  variables:
    DISPLAY: ':99'
  tags: 
    - linux
    - shell
  script:
    - cd software/tests/$TESTPROJECTNAME
    - qmake "QMAKE_CXXFLAGS += -fprofile-arcs -ftest-coverage" "QMAKE_LFLAGS += -fprofile-arcs -ftest-coverage" "CONFIG += doxygen"
    - make -j5
    - ./$TESTPROJECTNAME
    - gcovr -r ../../ -e .*moc_.+
  artifacts:
    untracked: true
    expire_in: 1 day
  before_script:
    - Xvfb :99 -screen 0 1920x1080x24 +extension GLX +render -noreset || echo "Process was already running."

## Run and build the tests ##

linux:test:exampleqtquicktest:
  <<: *linux_test_job
  stage: repoTest
  variables:
    DISPLAY: ':99'
    TESTPROJECTNAME: 'exampleqtquicktest'

linux:test:exampleqttest:
  <<: *linux_test_job
  stage: repoTest
  variables:
    DISPLAY: ':99'
    TESTPROJECTNAME: 'exampleqttest'

linux:test:praktikum1:
  <<: *linux_test_job
  stage: praktikum1
  variables:
    DISPLAY: ':99'
    TESTPROJECTNAME: 'praktikum1test'

linux:test:praktikum2:
  <<: *linux_test_job
  stage: praktikum2
  variables:
    DISPLAY: ':99'
    TESTPROJECTNAME: 'praktikum2test'
